[build]
  base = "frontend"
  command = "npm install; npm run build; ls -la"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Not = [{"Path": ["/api/*", "/static/*", "/assets/*"]}]} 